name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ========================
      #   FRONTEND (VITE)
      # ========================
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Frontend Dependencies
        run: |
          cd client
          npm install

      - name: Build Frontend
        run: |
          cd client
          npm run build

      - name: Upload Frontend Files
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "client/dist/"
          target: "/var/www/html/"
          strip_components: 1
  

      # ========================

      #   BACKEND (TYPESCRIPT)
      # ========================
      - name: Upload Backend Code
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "server/"
          target: "/var/www/"

      - name: Install, Build & Restart Backend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/server
            npm install
            npm run build
            pm2 restart backend || pm2 start dist/server.js --name backend
            pm2 save

